
version: '3.9'

networks:
  elastic-net:
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es-container
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=true"
      - "network.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kb-container
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=https://elasticsearch:9200"
      - "ELASTICSEARCH_USERNAME=kibana_system"
      - "ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}"
      - "NODE_OPTIONS=--max-old-space-size=512"
      - "XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTION_KEY_SAVED}"
      - "XPACK_SECURITY_ENCRYPTIONKEY=${ENCRYPTION_KEY_SECURITY}"
      - "XPACK_REPORTING_ENCRYPTIONKEY=${ENCRYPTION_KEY_REPORTING}"
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local
